# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\Projects\py_tools\copyer\copyer_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets

from copyer import copy_signal_file, copy_multi_file
from copyer.copyer_threads import OpenFileDialogThread


class Ui_Copyer(object):

    def setupUi(self, Copyer):
        Copyer.setObjectName("Copyer")
        Copyer.resize(777, 500)
        self.main_widget = QtWidgets.QWidget(Copyer)
        self.main_widget.setObjectName("main_widget")
        self.decrypt_signal_file = QtWidgets.QRadioButton(self.main_widget)
        self.decrypt_signal_file.setGeometry(QtCore.QRect(20, 20, 115, 19))
        self.decrypt_signal_file.setChecked(True)
        self.decrypt_signal_file.setObjectName("decrypt_signal_file")
        self.decrypt_multi_files = QtWidgets.QRadioButton(self.main_widget)
        self.decrypt_multi_files.setGeometry(QtCore.QRect(180, 20, 211, 19))
        self.decrypt_multi_files.setObjectName("decrypt_multi_files")
        self.stackedWidget = QtWidgets.QStackedWidget(self.main_widget)
        self.stackedWidget.setGeometry(QtCore.QRect(20, 50, 741, 391))
        self.stackedWidget.setObjectName("stackedWidget")
        self.signal_file_page = QtWidgets.QWidget()
        self.signal_file_page.setObjectName("signal_file_page")
        self.signal_file_selector_btn = QtWidgets.QPushButton(self.signal_file_page)
        self.signal_file_selector_btn.setGeometry(QtCore.QRect(0, 0, 121, 28))
        self.signal_file_selector_btn.setObjectName("signal_file_selector_btn")
        self.signal_file_decrypt_dest_dir_selector_btn = QtWidgets.QPushButton(self.signal_file_page)
        self.signal_file_decrypt_dest_dir_selector_btn.setGeometry(QtCore.QRect(0, 50, 121, 28))
        self.signal_file_decrypt_dest_dir_selector_btn.setObjectName("signal_file_decrypt_dest_dir_selector_btn")
        self.signal_file_textarea = QtWidgets.QTextBrowser(self.signal_file_page)
        self.signal_file_textarea.setGeometry(QtCore.QRect(0, 100, 721, 192))
        self.signal_file_textarea.setObjectName("signal_file_textarea")
        self.signal_file_label = QtWidgets.QLabel(self.signal_file_page)
        self.signal_file_label.setGeometry(QtCore.QRect(140, 0, 581, 28))
        self.signal_file_label.setText("")
        self.signal_file_label.setObjectName("signal_file_label")
        self.signal_file_dest_dir_label = QtWidgets.QLabel(self.signal_file_page)
        self.signal_file_dest_dir_label.setGeometry(QtCore.QRect(140, 50, 581, 28))
        self.signal_file_dest_dir_label.setText("")
        self.signal_file_dest_dir_label.setObjectName("signal_file_dest_dir_label")
        self.start_decrypt_signal_file = QtWidgets.QPushButton(self.signal_file_page)
        self.start_decrypt_signal_file.setGeometry(QtCore.QRect(630, 350, 90, 40))
        self.start_decrypt_signal_file.setObjectName("start_decrypt_signal_file")
        self.stackedWidget.addWidget(self.signal_file_page)
        self.multi_file_page = QtWidgets.QWidget()
        self.multi_file_page.setObjectName("multi_file_page")
        self.multi_file_dest_dir_label = QtWidgets.QLabel(self.multi_file_page)
        self.multi_file_dest_dir_label.setGeometry(QtCore.QRect(140, 50, 581, 28))
        self.multi_file_dest_dir_label.setText("")
        self.multi_file_dest_dir_label.setObjectName("multi_file_dest_dir_label")
        self.multi_file_dir_label = QtWidgets.QLabel(self.multi_file_page)
        self.multi_file_dir_label.setGeometry(QtCore.QRect(140, 0, 581, 28))
        self.multi_file_dir_label.setText("")
        self.multi_file_dir_label.setObjectName("multi_file_dir_label")
        self.multi_file_textarea = QtWidgets.QTextBrowser(self.multi_file_page)
        self.multi_file_textarea.setGeometry(QtCore.QRect(0, 100, 721, 192))
        self.multi_file_textarea.setObjectName("multi_file_textarea")
        self.start_decrypt_multi_file = QtWidgets.QPushButton(self.multi_file_page)
        self.start_decrypt_multi_file.setGeometry(QtCore.QRect(630, 350, 90, 40))
        self.start_decrypt_multi_file.setObjectName("start_decrypt_multi_file")
        self.multi_file_dir_selector_btn = QtWidgets.QPushButton(self.multi_file_page)
        self.multi_file_dir_selector_btn.setGeometry(QtCore.QRect(0, 0, 121, 28))
        self.multi_file_dir_selector_btn.setObjectName("multi_file_dir_selector_btn")
        self.multi_file_decrypt_dest_dir_selector_btn = QtWidgets.QPushButton(self.multi_file_page)
        self.multi_file_decrypt_dest_dir_selector_btn.setGeometry(QtCore.QRect(0, 50, 121, 28))
        self.multi_file_decrypt_dest_dir_selector_btn.setObjectName("multi_file_decrypt_dest_dir_selector_btn")
        self.multi_file_num_lcd = QtWidgets.QLCDNumber(self.multi_file_page)
        self.multi_file_num_lcd.setGeometry(QtCore.QRect(80, 310, 64, 23))
        self.multi_file_num_lcd.setObjectName("multi_file_num_lcd")
        self.multi_file_num_label = QtWidgets.QLabel(self.multi_file_page)
        self.multi_file_num_label.setGeometry(QtCore.QRect(0, 310, 70, 23))
        self.multi_file_num_label.setObjectName("multi_file_num_label")
        self.multi_file_decrypt_progress = QtWidgets.QProgressBar(self.multi_file_page)
        self.multi_file_decrypt_progress.setGeometry(QtCore.QRect(0, 350, 181, 23))
        self.multi_file_decrypt_progress.setProperty("value", 0)
        self.multi_file_decrypt_progress.setObjectName("multi_file_decrypt_progress")
        self.stackedWidget.addWidget(self.multi_file_page)
        Copyer.setCentralWidget(self.main_widget)
        self.menubar = QtWidgets.QMenuBar(Copyer)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 777, 26))
        self.menubar.setObjectName("menubar")
        Copyer.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Copyer)
        self.statusbar.setObjectName("statusbar")
        Copyer.setStatusBar(self.statusbar)

        self.retranslateUi(Copyer)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Copyer)

        self.decrypt_signal_file.toggled.connect(self.on_radio_button_toggled)
        self.decrypt_multi_files.toggled.connect(self.on_radio_button_toggled)
        self.signal_file_selector_btn.clicked.connect(self.on_signal_file_selector)
        self.signal_file_decrypt_dest_dir_selector_btn.clicked.connect(self.on_signal_file_decrypt_dest_dir_selector)
        self.start_decrypt_signal_file.clicked.connect(self.on_start_decrypt_signal_file)

        self.multi_file_dir_selector_btn.clicked.connect(self.on_multi_file_dir_selector_btn)
        self.multi_file_decrypt_dest_dir_selector_btn.clicked.connect(self.on_multi_file_decrypt_dest_dir_selector)
        self.start_decrypt_multi_file.clicked.connect(self.on_start_decrypt_multi_file)

    def on_radio_button_toggled(self):
        if self.decrypt_signal_file.isChecked():
            self.stackedWidget.setCurrentIndex(0)
        elif self.decrypt_multi_files.isChecked():
            self.stackedWidget.setCurrentIndex(1)

    def on_signal_file_selector(self):
        self.open_file_dialog_thread = OpenFileDialogThread()
        self.open_file_dialog_thread.signal.connect(lambda x: {
            self.signal_file_label.setText(x)
        })
        self.open_file_dialog_thread.file_type = "1"
        self.open_file_dialog_thread.start()

    def on_signal_file_decrypt_dest_dir_selector(self):
        self.open_file_dialog_thread = OpenFileDialogThread()
        self.open_file_dialog_thread.signal.connect(lambda x: {
            self.signal_file_dest_dir_label.setText(x)
        })
        self.open_file_dialog_thread.file_type = "2"
        self.open_file_dialog_thread.start()

    def on_start_decrypt_signal_file(self):
        copy_signal_file.decrypt_signal_file(self.signal_file_label.text(),
                                             self.signal_file_dest_dir_label.text(),
                                             lambda source_file, destination_folder: {
                                                 self.signal_file_textarea.append(
                                                     f"文件 '{source_file}' 已复制到目标目录 '{destination_folder}' 中。\n")
                                             })

    def on_multi_file_dir_selector_btn(self):
        self.open_file_dialog_thread = OpenFileDialogThread()
        self.open_file_dialog_thread.signal.connect(lambda x: {
            self.multi_file_dir_label.setText(x)
        })
        self.open_file_dialog_thread.file_type = "2"
        self.open_file_dialog_thread.start()

    def on_multi_file_decrypt_dest_dir_selector(self):
        self.open_file_dialog_thread = OpenFileDialogThread()
        self.open_file_dialog_thread.signal.connect(lambda x: {
            self.multi_file_dest_dir_label.setText(x)
        })
        self.open_file_dialog_thread.file_type = "2"
        self.open_file_dialog_thread.start()

    def on_start_decrypt_multi_file(self):
        copy_multi_file.decrypt_multi_file(self.multi_file_dir_label.text(),
                                           self.multi_file_dest_dir_label.text(),
                                           self.on_start_decrypt_multi_file_callback)

    def on_start_decrypt_multi_file_callback(self, count, files, source_file, dest_file):
        self.multi_file_num_lcd.display(count)
        self.multi_file_textarea.append(
            f"文件 '{source_file}' 已复制到目标目录 '{dest_file}' 中。\n")

    def retranslateUi(self, Copyer):
        _translate = QtCore.QCoreApplication.translate
        Copyer.setWindowTitle(_translate("Copyer", "文件解密器"))
        self.decrypt_signal_file.setText(_translate("Copyer", "解密单个文件"))
        self.decrypt_multi_files.setText(_translate("Copyer", "解密文件夹下所有文件"))
        self.signal_file_selector_btn.setText(_translate("Copyer", "选择文件"))
        self.signal_file_decrypt_dest_dir_selector_btn.setText(_translate("Copyer", "选择解密位置"))
        self.start_decrypt_signal_file.setText(_translate("Copyer", "开始解密"))
        self.start_decrypt_multi_file.setText(_translate("Copyer", "开始解密"))
        self.multi_file_dir_selector_btn.setText(_translate("Copyer", "选择文件夹"))
        self.multi_file_decrypt_dest_dir_selector_btn.setText(_translate("Copyer", "选择解密位置"))
        self.multi_file_num_label.setText(_translate("Copyer", "文件个数"))
